apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/part-of: ephemeralvolumeautocleanup
    app.kubernetes.io/instance: manager
  name: {{ include "ephemeral-volume-cleanup.clusterole.name" . }}
rules:
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies/finalizers"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "list", "update", "delete", "patch", "get", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch", "get"]