apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ephemeral-volume-cleanup.serviceaccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/part-of: ephemeralvolumeautocleanup
    app.kubernetes.io/instance: manager
